### ISSUE TITLE
Cannot open job scheduling details

### ISSUE THREAD

**Issue by simone-pignotti** [aws/aws-parallelcluster-ui#109]
## Description
When I click on the ID of a job in the "job scheduling" tab, I get an error message and cannot see job details.

## Steps to reproduce the issue
Go to the job scheduling tab of an active cluster and try to open one of the jobs (does not depend on job status).

## Expected behaviour
Show job information.

## Actual behaviour
I always land on the following error alert:
```
Something went wrong

The application has encountered an unknown error and it is now in an inconsistent state. If you think that this is an error on our side, please help us improve by sending an error report on our GitHub issues page. Close this dialog to go back to the home page.
```
Then I get redirected to the dashboard.

## Required info
- Region where ParallelCluster UI is installed: eu-west-3
- Version of ParallelCluster UI and ParallelCluster: 3.5.0

## Additional info
 - OS: MacOS
 - Browser: chrome

**Comment by mtfranchetto** [comment]
Hi @simone-pignotti, I confirm sometimes the Job modal can show this error when any of these job properties are not available:
- WorkDir
- StdOut
- StdErr

I'll work on a fix as soon as possible.
