### ISSUE TITLE
PCUI not deploying in us-east-2

### ISSUE THREAD

**Issue by ahoppeumgc** [aws/aws-parallelcluster-ui#241]
**Before submitting a ticket, please search through the following resources:**
- [Official documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcui-using-v3.html)
- [Issues](https://github.com/aws/aws-parallelcluster-ui/issues)

## Description
PCUI not deploying in us-east-2

## Steps to reproduce the issue
Opened us-east-2 link:
https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/create/review?stackName=parallelcluster-ui&templateURL=https://parallelcluster-ui-release-artifacts-us-east-1.s3.us-east-1.amazonaws.com/parallelcluster-ui.yaml

Stack created, email received, password updated, but then this pop-up shows: 
Something went wrong
The application has encountered an unknown error and it is now in an inconsistent state. etc.

Clicking on go to homepage button brings it up again ad infinitum

## Expected behaviour
Describe what you expected to happen

## Actual behaviour
Describe what happened instead. Please include, if relevant, any of the following:
Something went wrong
The application has encountered an unknown error and it is now in an inconsistent state. etc.

## Required info
In order to help us determine the root cause of the issue, please provide the following information:
- Region where ParallelCluster UI is installed
- Version of ParallelCluster UI and ParallelCluster (follow [this guide](https://docs.aws.amazon.com/parallelcluster/parallelcluster/latest/ug/install-pcui-v3.html) to see what's installed)
- Logs

## Additional info
The following information is not required but helpful:
 - macos, firefox

## If having problems with cluster creation or update
YAML file generated by the ParallelCluster UI

## If having problems with custom image creation
YAML file of the custom image

**Comment by mtfranchetto** [comment]
Hello @ahoppeumgc,
I deployed a fresh PCUI in `us-east-2` but everything works well.
I need additional info to help you troubleshoot the issue:
- the ParallelCluster version you've installed along PCUI
- if you already have existing clusters in that region
- if you are using an external Cognito user pool
- it would help a lot to have the application logs too - follow [this guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3-get-runtime-logs.html) to extract the logs

**Comment by ahoppeumgc** [comment]
It happens when installing PCUI, no luck with clusters yet - I can't stay in PCUI home.
I tried using us-west2 and eu-central too, same thing - something went wrong.
No external user pool.
Default versions as per the template
Logs attached, along with template  (not sure for which region)
[logs-insights-results.json.zip](https://github.com/aws/aws-parallelcluster-ui/files/11758616/logs-insights-results.json.zip)
[parallelcluster-ui(1).yaml.zip](https://github.com/aws/aws-parallelcluster-ui/files/11758624/parallelcluster-ui.1.yaml.zip)

**Comment by mtfranchetto** [comment]
Thank you. I'll look at the logs. In the meantime, make sure you have at least `100` concurrent executions set on AWS Lambda Service Quotas. Visit the Service Quota dashboard from the console to check the current value, and to increase it if necessary.

**Comment by ahoppeumgc** [comment]
It looks like it was a browser issue - I tried in Safari and it worked! I was able to install PCUI and create/run a cluster.
My Forefox setup is pretty standard, dunno what happened.

I am preparing a PC lab in UMGC Cloud Computing Systems program class - CCS 670. Will tell students not to use Firefox?
Thanks!

**Comment by mtfranchetto** [comment]
I'm closing the issue since the original problem has been resolved. Feel free to open a new one if you have other requests.

**Comment by ryanslabxyz** [comment]
For what it's worth, I got the same issue loading a new deployment when using Firefox on Ubuntu. I installed Chromium and it worked. When I used Firefox it flashed the clusters menu but then a popup appeared saying something went wrong and to open a Github issue. I tried Firefox private too.
