### ISSUE TITLE
Feature Request: Fargate based implementation

### ISSUE THREAD

**Issue by vvvgill** [aws/aws-parallelcluster-ui#257]
Currently the UI implementation is based on API gateway and it has proven pretty difficult to incorporate  our OIDC based authentication with parallel cluster UI. Application load balancer integration with cognito solves our use case but we need to somehow make the UI backend sit on fargate as ALB cannot target api gateway. Is it possible for us to get a simple container based implementation running a server. 

I am not that well versed with Cognito  OIDC and api gateway integration. Is it possible for the parallellcluster UI backend to authenticate an unauthenticated user using Cognito + OIDC provider integration ?

**Comment by BarcoMasile** [comment]
Hi, thank you for writing to us.
A fargate based implementation is not in our roadmap unfortunately.
We have a public ECR registry with the PCUI container (the one that gets deployed by the Cloudformation 1-click link.
Here is the [link](https://gallery.ecr.aws/pcm/parallelcluster-ui), you can use the container directly for you customization in the infrastructure.

About Cognito, when you deploy PCUI you also get a Cognito user pool. You can access the user pool from the console in the same region in which you deployed PCUI and set up a federation to an external OIDC provider of you choice. Keep in mind this is not a use case we support at the moment, but I know there's a lot of resources to help you with this.

I hope this is helpful.
