### ISSUE TITLE
Trying to delete a ParallelCluster UI cloudformation stack may fail due to ECR repository images list not being empty and needing manual deletion

### ISSUE THREAD

**Issue by BarcoMasile** [aws/aws-parallelcluster-ui#33]
When deleting a whole PCUI cloudformation stack, the ECRPrivateEcrRepo cannot be deleted because it still contain at least one image, so the whole stack goes into the DELETE_FAILED state.

Seems like the custom resource that deletes the private Ecr Repo has some issues.

#### Workaround
Go to the ECR console and delete all images from the aforementioned Private ECR Repository.
Then go back to CloudFormation and try deleting the stack again. It will succeed

**Comment by crabba** [comment]
Superfluous '+1' comment due to lack of +1 button in GH Issues.
