### ISSUE TITLE
Opening the wizard to create a cluster will present the same source option selected from the last time it was opened in the same session

### ISSUE THREAD

**Issue by BarcoMasile** [aws/aws-parallelcluster-ui#34]
When a source option is chosen in the initial step of the wizard, if you exit the wizard (probably in any way so by either clicking "Esc" key, select "cancel" or completing the creation of a wizard) and then try to create a new cluster, the previous selection is already selected.

### Steps to reproduce
- create a cluster using one of the last 2 source types
- reach completion
- see your new cluster in creating state
- click "Create" to visualize the wizard and notice that the last option you clicked is selected already

**Comment by lazyoft** [comment]
Fixed by #94
